feat(commands): message clear command
Naval-Base/yuudachi pull request #1083
Opened 2022-07-31 15:08 UTC by almostSouji

Introduce a command to clear messages in a provided range
- 1 message: clear up to and include this message
- 2 messages: clear in range between and including both messages
- 12h in the past max to safeguard (accidental) abuse
- Verbose confirmation flow

![image](https://user-images.githubusercontent.com/26532370/182032668-04b301a6-3ca4-459c-85c9-3beeb7bb27ae.png)

2022-07-31 20:18 UTC, iCrawl requested changes

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/locales/en-US/translation.json
> +				"not_message_id": "Provided value `{{- val}}` for argument `{{- arg}}` is not a valid message id."
```suggestion
				"not_message_id": "Provided value `{{val}}` for argument `{{arg}}` is not a valid message id."
```

No need for this.

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/locales/en-US/translation.json
> +					"execute_plural": "Clear {{count}} messages"
This works a bit different in i18next: https://www.i18next.com/translation-function/plurals#singular-plural

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +import { ButtonStyle, CommandInteraction, ComponentType } from 'discord.js';
```suggestion
import { ButtonStyle, type CommandInteraction, ComponentType } from 'discord.js';
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +					arg: 'from',
```suggestion
					val: args.last_message,
					arg: 'from',
					lng: locale,
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +					arg: 'to',
```suggestion
					val: args.first_message,
					arg: 'to',
					lng: locale,
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +					channel: interaction.channel!.toString(),
```suggestion
					message_id: args.last_message,
					// eslint-disable-next-line @typescript-eslint/no-base-to-string
					channel: interaction.channel!.toString(),
					lng: locale,
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +							channel: interaction.channel!.toString(),
```suggestion
							message_id: args.first_message,
							// eslint-disable-next-line @typescript-eslint/no-base-to-string
							channel: interaction.channel!.toString(),
							lng: locale,
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +		const clearButton = createButton({
```suggestion
		const clearKey = nanoid();
		const cancelKey = nanoid();

		const clearButton = createButton({
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +			label: i18next.t('command.mod.clear.buttons.execute', { lng: locale, count: messages.size }),
```suggestion
			label: i18next.t('command.mod.clear.buttons.execute', { count: messages.size, lng: locale }),
```

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/functions/pruning/pruneMessages.ts
> +		});
Intended?

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/functions/pruning/pruneMessages.ts
> +	console.log('res size: ', res.size);
Same

2022-07-31 20:18 UTC, iCrawl commented on packages/yuudachi/src/functions/pruning/pruneMessages.ts
> +	console.log(messages.map((m) => `${m.author.tag}: ${m.content}`).join('\n'));
Same

2022-07-31 22:57 UTC, almostSouji commented
Waiting for https://github.com/Naval-Base/yuudachi/pull/1080 to be merged, so this can build on the extended message logs when logging the clear as a separate action in guild logs.

2022-08-01 18:00 UTC, iCrawl commented on packages/yuudachi/src/commands/moderation/clear.ts
> +import { ButtonStyle, CommandInteraction, ComponentType } from 'discord.js';
```suggestion
import { ButtonStyle, type CommandInteraction, ComponentType } from 'discord.js';
```

2022-08-01 19:44 UTC, merged